# dataset
dataset: frame

data_dir: /path/to/dataset/videos # s
audio_dir: /path/to/dataset/audio
pretrained_model_path: /path/to/checkpoints/latte

# save and load
results_dir: ./results
pretrained: 

# model config: 
model: VDT-B/2
num_frames: 16
initial_frames: 0
clip_frames: 16
frame_interval: 1
fixed_spatial: False
image_size: 256
in_channels: 4
temp_comp_rate: 1
num_sampling_steps: 250
learn_sigma: True # important
extras: 1 # [1, 2] 1 unconditional generation, 2 class-conditional generation
use_seque: False
audio_margin: 2
audio_dim: 768
audio_token: 32

precision: bf16   # GPU Axx: bf16-mixed

# train config:
save_ceph: True # important
learning_rate: 1e-4
ckpt_every: 100000
clip_max_norm: 0.1
start_clip_iter: 20000
local_batch_size: 1 # important
max_train_steps: 300000
global_seed: 3407
num_workers: 8
log_every: 50
lr_warmup_steps: 0
resume_from_checkpoint:
gradient_accumulation_steps: 1 # TODO
num_classes:

# low VRAM and speed up training
use_compile: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: False